spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: tibid
    password: tibid
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
hibernate:
  dialect: org.hibernate.dialect.H2Dialect
  show_sql: true
  hbm2ddl:
    auto: create-drop
  cache:
    use_second_level_cache: true
    use_query_cache: true
    region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
server:
  port: 8080

kafka:
  bootstrapAddress: localhost:9092
  topic:
    name:
     bidorder: bid_order_status
     bidticket: bid_ticket_status