spring:
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
        hbm2ddl:
          auto: create
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    show_sql: true
  datasource:
    url: jdbc:mariadb://localhost:9083/tibid
    driver-class-name: org.mariadb.jdbc.Driver
    username: tibid
    password: tibid

tiki:
  base-url: https://api.tiki.vn/tiniapp-open-api
  create-order-path: /order
  exchange-auth-token: /oauth/auth/token
  order-complete: /order/complete
  client-id: wlEvLJ3wiIIlyaHIIGJzNhnwEE3LV795
  client-secret: q9@Hdc8tnXWjLdDr915tf3GB8mDlqGEjduW@zs6LHb_suxsR~t_/7yvuJ/2:p18x

server:
  port: 8080