spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
    username: tibid
    password: tibid
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080