spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: create
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    show_sql: true
  datasource:
    user: tibid
    password: tibid
    url: jdbc:mysql://35.240.222.157:3306/tbid
    driver-class-name: com.mysql.cj.jdbc.Driver
    continue-on-error: true
    initialization-mode: always
  cloud:
    gcp:
      sql:
        instance-connection-name: hackathon-15-tibid:asia-southeast1:tibid
        database-name: tbid

tiki:
  base-url: https://api.tiki.vn/tiniapp-open-api
  create-order-path: /order
  exchange-auth-token: /oauth/auth/token
  order-complete: /order/complete
  client-id: wlEvLJ3wiIIlyaHIIGJzNhnwEE3LV795
  client-secret: q9@Hdc8tnXWjLdDr915tf3GB8mDlqGEjduW@zs6LHb_suxsR~t_/7yvuJ/2:p18x

server:
  port: 8080
